config/routes.rb
Rails.application.routes.draw do
  devise_for :companies, path: 'companies', controllers: {
    sessions: 'companies/sessions'
  }
  devise_for :users, path: 'users', controllers: {
    sessions: 'users/sessions'
  }
  root to: 'pages#home'
  get 'pages/applicant_welcome', as: 'applicant_welcome'
  get 'pages/about_us', as: 'about_us'
  resources :user_profiles, only: [:show, :new, :create, :edit, :update] do
    resources :user_studies, only: [:index, :new, :create, :destroy, :edit, :update]
    resources :user_other_studies, only: [:index, :new, :create, :destroy, :edit, :update]
    resources :user_languages, only: [:index, :new, :create, :destroy, :edit, :update]
    resources :work_preferences, only: [:index, :new, :create, :destroy, :edit, :update]
    resources :user_skills, only: [:index, :new, :create, :destroy]
    resources :user_experiences, only: [:index, :new, :create, :destroy, :edit, :update]
    resources :user_traits, only: [:index, :new, :create, :destroy]
    resources :user_hobbies, only: [:index, :new, :create, :destroy, :edit, :update]
  end

end

app/models/user_hobby.rb
class UserHobby < ApplicationRecord
  belongs_to :user_profile

  CATEGORY = ["Collecting", "Making and Tinkering", "Outdoor Recreation",
              "Gardening", "Liberal Arts Pursuits", "Sports and Games",
              "Indoor Recreation", "Other"]

  validates :name, presence: true
  validates :category, presence: true, inclusion: { in: CATEGORY }
end

app/controllers/user_hobbies_controller.rb
class UserHobbiesController < ApplicationController
  def new
    @profile = UserProfile.find(params[:user_profile_id])
    @hobby = UserHobby.new
  end

  def index
    @profile = UserProfile.find(params[:user_profile_id])
    @hobby = UserHobby.where(user_profile_id: params[:user_profile_id])
  end

  def create
    @profile = UserProfile.find(params[:user_profile_id])
    @hobby = UserHobby.new(hobby_params)
    @hobby.user_profile = current_user.user_profile
    if @hobby.save
      redirect_to user_profile_path(:user_profile_id)
      flash[:notice] = "Hobby Added"
    else
      flash[:alert] = "Please verify the following information:"
      render :new
      puts @hobby.errors.full_messages
    end
  end

  def destroy
    @hobby = UserHobby.find(params[:id])
    @hobby.destroy
    redirect_to user_profile_path(:user_profile_id)
    flash[:alert] = "Hobby Removed"
  end

  def edit
    @profile = UserProfile.find(params[:user_profile_id])
    @hobby = UserHobby.find(params[:id])
  end

  def update
    @profile = UserProfile.find(params[:user_profile_id])
    @hobby = UserHobby.find(params[:id])
    @hobby.update(hobby_params)
    if @hobby.save
      redirect_to user_profile_path(:user_profile_id)
      flash[:notice] = "Hobby Updated"
    else
      flash[:alert] = "Please verify the following information:"
      render :new
      puts @hobby.errors.full_messages
    end
  end

  private

  def hobby_params
    params.require(:user_hobby).permit(:user_profile_id, :name, :category)
  end
end

app/views/user_hobbies/_form.html.erb
<%= simple_form_for [@profile, @hobby] do |f| %>
<%= f.input :name %>
<%= f.input :category, collection: ["Collecting", "Making and Tinkering",
                                    "Outdoor Recreation", "Gardening",
                                    "Liberal Arts Pursuits", "Sports and Games",
                                    "Indoor Recreation", "Other"] %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/user_hobbies/edit.html.erb
<div class="container-fluid gradient">
  <div class="row">
    <div class="col-12 col-md-8 offset-md-2 col-lg-6 offset-lg-3">
      <div class="form-login">

        <h2 class="text-center">Edit Hobby</h2>

        <%= render 'form' %>
        <%= link_to "Cancel", user_profile_path(current_user.user_profile.id),
        class: "btn btn-light" %>
        <%= link_to "Remove", user_profile_user_hobby_path(params[:id]),
        method: :delete, class: "btn btn-danger" %>
      </div>
    </div>
  </div>
</div>

app/views/user_hobbies/index.html.erb
<div class="container-fluid gradient-profile">
  <div class="row">
    <div class="col-12 col-md-8 offset-md-2 col-lg-6 offset-lg-3">
      <div class="form-profile">
        <nav class="nav nav-pills nav-fill">
          <%= link_to "About Me", user_profile_path(current_user.user_profile.id),
          class: "nav-item nav-link" %>
          <%= link_to "Education", user_profile_user_studies_path(current_user.user_profile.id),
          class: "nav-item nav-link" %>
          <%= link_to "Certifications", user_profile_user_other_studies_path(current_user.user_profile.id), class: "nav-item nav-link" %>
          <%= link_to "Languages", user_profile_user_languages_path(current_user.user_profile.id),
          class: "nav-item nav-link" %>
          <%= link_to "Work Preferences", user_profile_work_preferences_path(current_user.user_profile.id), class: "nav-item nav-link" %>
          <%= link_to "Skills", user_profile_user_skills_path(current_user.user_profile.id),
          class: "nav-item nav-link" %>
          <%= link_to "Working Experience", user_profile_user_experiences_path(current_user.user_profile.id), class: "nav-item nav-link" %>
          <%= link_to "Personality Traits", user_profile_user_traits_path(current_user.user_profile.id), class: "nav-item nav-link" %>
          <%= link_to "Hobbies", user_profile_user_hobbies_path(current_user.user_profile.id),
          class: "nav-item nav-link active" %>
        </nav>
       <h3>
          Hobbies
          <%= link_to new_user_profile_user_hobby_path(current_user.user_profile.id),
          class: "btn-add" do %>
            <i class="fas fa-plus"></i>
          <% end %>
        </h3>
        <% @hobby.each_with_index do |t, i| %>
          <h4>
            <%= t.name %>
            <%= link_to edit_user_profile_user_hobby_path(@profile, t.id),
            class: "btn-add" do %>
            <i class="far fa-edit"></i>
            <% end %>
          </h4>
          <p>
            <strong>Category:</strong>
            <%= t.category %>
          </p>
          <% if i < @hobby.size - 1 %>
            <hr>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/user_hobbies/new.html.erb
<div class="container-fluid gradient">
  <div class="row">
    <div class="col-12 col-md-8 offset-md-2 col-lg-6 offset-lg-3">
      <div class="form-login">

        <h2 class="text-center">Add a Hobby to your Profile</h2>

        <%= render 'form' %>
        <%= link_to "Cancel", user_profile_path(current_user.user_profile.id),
        class: "btn btn-light" %>
      </div>
    </div>
  </div>
</div>