config/routes.rb
Rails.application.routes.draw do
  devise_for :companies, path: 'companies', controllers: {
    sessions: 'companies/sessions'
  }
  devise_for :users, path: 'users', controllers: {
    sessions: 'users/sessions'
  }
  root to: 'pages#home'
  get 'pages/applicant_welcome', as: 'applicant_welcome'
  get 'pages/about_us', as: 'about_us'
  resources :user_profiles, only: [:show, :new, :create, :edit, :update] do
    resources :user_studies, only: [:index, :new, :create, :destroy, :edit, :update]
    resources :user_other_studies, only: [:index, :new, :create, :destroy, :edit, :update]
    resources :user_languages, only: [:index, :new, :create, :destroy, :edit, :update]
    resources :work_preferences, only: [:index, :new, :create, :destroy, :edit, :update]
    resources :user_skills, only: [:index, :new, :create, :destroy]
    resources :user_experiences, only: [:index, :new, :create, :destroy, :edit, :update]
    resources :user_traits, only: [:index, :new, :create, :destroy]
    resources :user_hobbies, only: [:index, :new, :create, :destroy, :edit, :update]
  end

end

app/models/user_profile.rb
class UserProfile < ApplicationRecord
  belongs_to :user
  has_many :user_studies, dependent: :destroy
  has_many :studies, through: :user_studies
  has_many :user_other_studies, dependent: :destroy
  has_many :other_studies, through: :user_other_studies
  has_many :user_languages, dependent: :destroy
  has_many :languages, through: :user_languages
  has_many :work_preferences, dependent: :destroy
  has_many :user_skills, dependent: :destroy
  has_many :skills, through: :user_skills
  has_many :user_experiences, dependent: :destroy
  # has_many :positions, through: :user_experiences
  has_many :user_traits, dependent: :destroy
  has_many :traits, through: :user_traits
  has_many :user_hobbies

  VISA = ["Australian Resident", "Student Visa", "Working Holiday Visa"]

  validates :name, presence: true, length: { minimum: 2 }
  validates :last_name, presence: true, length: { minimum: 2 }
  validates :birth_date, presence: true
  validates :sex, presence: true, inclusion: { in: %w(Male Female Other) }
  validates :phone, presence: true, numericality: { only_integer: true }
  validates :residency_status, presence: true
  validates :residency_status, inclusion: { in: VISA }
  validates :origin_country, presence: true
  validates :residence_country, presence: true
  validates :address, presence: true

  mount_uploader :photo, PhotoUploader
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/user_profiles_controller.rb
class UserProfilesController < ApplicationController
  def show
    @user = current_user
    @profile = @user.user_profile
    @user_studies = @profile.user_studies
    @user_other_studies = @profile.user_other_studies
    @user_languages = @profile.user_languages
    @preferences = @profile.work_preferences
    @skills = @profile.user_skills
    @experiences = @profile.user_experiences
    @traits = @profile.user_traits
    @hobbies = @profile.user_hobbies
    time_delta = Time.now.to_i - @profile.birth_date.to_i
    @age = time_delta / 31_557_600 # seconds in a year
    @origin_country = country_name(@profile.origin_country)
    @residence_country = country_name(@profile.residence_country)
    respond_to do |format|
      format.html
      format.pdf do
        render  pdf: "CV - #{@profile.name} #{@profile.last_name}",
                template: "user_profiles/pdf_profile.html.erb",
                layout: 'pdf.html',
                disposition: 'attachment',
                no_background: true
      end
    end
  end

  def new
    @profile = UserProfile.new
  end

  def create
    @profile = UserProfile.new(profile_params)
    @profile.user = current_user
    if @profile.save
      redirect_to user_profile_path(:id)
    else
      render new_user_profile_path
      puts @profile.errors.full_messages
    end
  end

  def edit
    @profile = UserProfile.find(params[:id])
  end

  def update
    @profile = UserProfile.find(params[:id])
    @profile.update(profile_params)
    if @profile.save
      redirect_to user_profile_path(:user_profile_id)
      flash[:notice] = "Profile Updated"
    else
      flash[:alert] = "Please verify the following information:"
      render new_user_profile_path
      puts @profile.errors.full_messages
    end
  end

  private

  def profile_params
    params.require(:user_profile).permit(:user_id, :name, :last_name, :photo,
                                         :birth_date, :residency_status, :sex,
                                         :phone, :photo_cache, :origin_country,
                                         :residence_country, :address)
  end

  def country_name(country_code)
    CountryStateSelect.countries_collection.to_h.key(country_code.to_sym)
  end
end

app/views/user_profiles/_form.html.erb
<%= simple_form_for(@profile) do |f| %>
  <%= f.input :name, label: "First Name" %>
  <%= f.input :last_name %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.input :birth_date, as: :string, input_html:
  { class: 'datepicker birth_date' } %>
  <%= f.input :sex, collection: [:Male, :Female, :Other] %>
  <%= f.input :origin_country, collection:
  CountryStateSelect.countries_collection, label: "Country of Origin" %>
  <%= f.input :residency_status, collection: ["Australian Resident",
                                              "Student Visa",
                                              "Working Holiday Visa"] %>
  <%= f.input :phone, as: :tel %>
  <%= f.input :residence_country, collection:
  CountryStateSelect.countries_collection, label: "Country of Residence" %>
  <%= f.input :address, placeholder: "27 O'Connell St, Sydney" %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/user_profiles/edit.html.erb
<div class="container-fluid gradient">
  <div class="row">
    <div class="col-12 col-md-8 offset-md-2 col-lg-6 offset-lg-3">
      <div class="form-login">

        <h2 class="text-center">Edit your Profile</h2>

        <%= render 'form' %>
        <%= link_to "Cancel", user_profile_path(current_user.user_profile.id),
        class: "btn btn-light" %>
      </div>
    </div>
  </div>
</div>

app/views/user_profiles/new.html.erb
<div class="container-fluid gradient">
  <div class="row">
    <div class="col-12 col-md-8 offset-md-2 col-lg-6 offset-lg-3">
      <div class="form-login">

        <h2 class="text-center">Create a new Profile</h2>

        <%= render 'form' %>

      </div>
    </div>
  </div>
</div>

app/views/user_profiles/pdf_profile.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 col-md-8 offset-md-2 col-lg-6 offset-lg-3">

      <div class="pdf-box">
        <h2 class="text-center"><%= @profile.name %> <%= @profile.last_name %></h2>

        <% if @profile.photo? %>
          <%= wicked_pdf_image_tag @profile.photo, class: "photo" %>
        <% else %>
          <%= wicked_pdf_image_tag "profile.png", alt: "photo", height: "150px" %>
        <% end %>

        <p><strong>Age:</strong> <%= @age %></p>
        <p><strong>Sex:</strong> <%= @profile.sex %></p>
        <p><strong>Country of Origin:</strong> <%= @origin_country %></p>
        <p><strong>Residency Status:</strong> <%= @profile.residency_status %></p>
        <p><strong>E-mail:</strong> <%= @user.email %></p>
        <p><strong>Phone:</strong> <%= @profile.phone %></p>
        <p><strong>Country of Residence:</strong> <%= @residence_country %></p>
        <p><strong>Address:</strong> <%= @profile.address %></p>

      </div>

      <!-- Studies -->
      <div class="pdf-box">
        <h3>
          Education
        </h3>
        <% @user_studies.each_with_index do |s, i| %>
          <h4>
            <%= s.study.title %>
          </h4>
          <p>
            <%= s.start_date.strftime("%b %Y") %> - <%= s.end_date.strftime("%b %Y") %>
             |
            <%= s.duration %>
          </p>
          <p>
            <strong>Degree:</strong>
            <%= s.study_type %>
          </p>
          <p>
            <strong>Status:</strong>
            <%= s.status %>
          </p>
          <% if i < @user_studies.size - 1 %>
            <hr>
          <% end %>
        <% end %>
      </div>
      <!-- Other Studies -->
      <div class="pdf-box">
        <h3>
          Certifications
        </h3>
        <% @user_other_studies.each_with_index do |s, i| %>
          <h4>
            <%= s.other_study.title %>
          </h4>
          <p>
            <%= s.start_date.strftime("%b %Y") %> - <%= s.end_date.strftime("%b %Y") %>
             |
            <%= s.duration %>
          </p>
          <p>
            <strong>Type:</strong>
            <%= s.study_type %>
          </p>
          <% if i < @user_other_studies.size - 1 %>
            <hr>
          <% end %>
        <% end %>
      </div>
      <!-- Languages -->
      <div class="pdf-box">
        <h3>
          Languages
        </h3>
        <% @user_languages.each_with_index do |s, i| %>
          <h4>
            <%= s.language.name %>
          </h4>
          <p>
            <strong>Proficiency:</strong>
            <%= s.proficiency %>%
          </p>
          <% if i < @user_languages.size - 1 %>
            <hr>
          <% end %>
        <% end %>
      </div>
      <!-- Work Preferences -->
      <div class="pdf-box">
          <h3>
            Work Preferences
          </h3>
          <% @preferences.each_with_index do |s, i| %>
            <h4>
              <%= s.study.title %>
            </h4>
            <p>
              <strong>Contract Type:</strong>
              <%= s.contract_type %>
            </p>
            <p>
              <strong>Objectives:</strong>
              <%= s.objectives %>
            </p>
            <% if i < @preferences.size - 1 %>
              <hr>
            <% end %>
          <% end %>
      </div>
      <!-- Skills -->
      <div class="pdf-box">
          <h3>
            Skills
          </h3>
          <% @skills.each_with_index do |t, i| %>
            <h4>
              <%= t.skill.name %>
            </h4>
          <% end %>
      </div>
      <!-- Working Experience -->
      <div class="pdf-box">
          <h3>
            Working Experience
          </h3>
          <% @experiences.each_with_index do |s, i| %>
            <h4>
              <%= s.study.title %>
            </h4>
            <p>
              <%= s.company_name %>
            </p>
            <p>
              <%= s.start_date.strftime("%b %Y") %> - <%= s.end_date.strftime("%b %Y") %>
               |
              <%= s.duration %>
            </p>
            <p>
              <strong>Contract Type:</strong>
              <%= s.contract_type %>
            </p>
            <p>
              <strong>Description:</strong>
              <%= s.description %>
            </p>
            <p>
              <strong>Skills:</strong>
              <%= s.skill.name %>
            </p>
            <p>
              <strong>Status:</strong>
              <%= s.status %>
            </p>
            <% if i < @experiences.size - 1 %>
              <hr>
            <% end %>
          <% end %>
      </div>
      <!-- Traits -->
      <div class="pdf-box">
          <h3>
            Personality Traits
          </h3>
          <% @traits.each_with_index do |s, i| %>
            <h4>
              <%= s.trait.name %>
            </h4>
            <p>
              <strong>Description:</strong>
              <%= s.trait.description %>
            </p>
            <% if i < @traits.size - 1 %>
              <hr>
            <% end %>
          <% end %>
      </div>
      <!-- Hobby -->
      <div class="pdf-box">
          <h3>
            Hobbies
          </h3>
          <% @hobbies.each_with_index do |t, i| %>
            <h4>
              <%= t.name %>
            </h4>
            <p>
              <strong>Category:</strong>
              <%= t.category %>
            </p>
            <% if i < @hobbies.size - 1 %>
              <hr>
            <% end %>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/user_profiles/show.html.erb
<div class="container-fluid gradient-profile">
  <div class="row">
    <div class="col-12 col-md-8 offset-md-2 col-lg-6 offset-lg-3">

      <div class="form-profile">
        <h2 class="text-center">Welcome, <%= @profile.name %></h2>
        <nav class="nav nav-pills nav-fill">
          <%= link_to "About Me", user_profile_path(current_user.user_profile.id),
          class: "nav-item nav-link active" %>
          <%= link_to "Education", user_profile_user_studies_path(current_user.user_profile.id),
          class: "nav-item nav-link" %>
          <%= link_to "Certifications", user_profile_user_other_studies_path(current_user.user_profile.id), class: "nav-item nav-link" %>
          <%= link_to "Languages", user_profile_user_languages_path(current_user.user_profile.id),
          class: "nav-item nav-link" %>
          <%= link_to "Work Preferences", user_profile_work_preferences_path(current_user.user_profile.id), class: "nav-item nav-link" %>
          <%= link_to "Skills", user_profile_user_skills_path(current_user.user_profile.id),
          class: "nav-item nav-link" %>
          <%= link_to "Working Experience", user_profile_user_experiences_path(current_user.user_profile.id), class: "nav-item nav-link" %>
          <%= link_to "Personality Traits", user_profile_user_traits_path(current_user.user_profile.id), class: "nav-item nav-link" %>
          <%= link_to "Hobbies", user_profile_user_hobbies_path(current_user.user_profile.id),
          class: "nav-item nav-link" %>
        </nav>

        <h3>
          About Me
          <%= link_to edit_user_profile_path(@profile.id), class: "btn-add",
          "data-toggle" => "modal", "data-target" => "#" do %>
          <i class="far fa-edit"></i>
          <% end %>
        </h3>
        <% if @profile.photo? %>
        <%= cl_image_tag(@profile.photo, width: 150, height: 150, crop: :thumb,
        gravity: :face, radius: 75) %>
        <% else %>
        <%= image_tag "profile.png", alt: "photo", height: "150px" %>
        <% end %>
        <h5><%= @profile.name %> <%= @profile.last_name %></h5>
        <p><strong>Sex:</strong> <%= @profile.sex %></p>
        <p><strong>Age:</strong> <%= @age %></p>
        <p><strong>Country of Origin:</strong> <%= @origin_country %></p>
        <p><strong>Residency Status:</strong> <%= @profile.residency_status %></p>
        <p><strong>E-mail:</strong> <%= @user.email %></p>
        <p><strong>Phone:</strong> <%= @profile.phone %></p>
        <p><strong>Country of Residence:</strong> <%= @residence_country %></p>
        <p><strong>Address:</strong> <%= @profile.address %></p>
        <%= link_to 'Create PDF document', user_profile_path(@profile, :format => :pdf),
        class: "btn btn-primary" %>

      </div>

      <!-- Studies -->
      <div class="form-profile">
        <h3>
          Education
          <%= link_to new_user_profile_user_study_path(current_user.user_profile.id),
          class: "btn-add" do %>
          <i class="fas fa-plus"></i>
          <% end %>
        </h3>
        <% @user_studies.each_with_index do |s, i| %>
          <h4>
            <%= s.study.title %>
            <%= link_to edit_user_profile_user_study_path(@profile, s.id), class: "btn-add" do %>
            <i class="far fa-edit"></i>
            <% end %>
          </h4>
          <p>
            <%= s.start_date.strftime("%b %Y") %> - <%= s.end_date.strftime("%b %Y") %>
             |
            <%= s.duration %>
          </p>
          <p>
            <strong>Degree:</strong>
            <%= s.study_type %>
          </p>
          <p>
            <strong>Status:</strong>
            <%= s.status %>
          </p>
          <% if i < @user_studies.size - 1 %>
            <hr>
          <% end %>
        <% end %>
      </div>
      <!-- Other Studies -->
      <div class="form-profile">
        <h3>
          Certifications
          <%= link_to new_user_profile_user_other_study_path(current_user.user_profile.id),
          class: "btn-add" do %>
          <i class="fas fa-plus"></i>
          <% end %>
        </h3>
        <% @user_other_studies.each_with_index do |s, i| %>
          <h4>
            <%= s.other_study.title %>
            <%= link_to edit_user_profile_user_other_study_path(@profile, s.id), class: "btn-add" do %>
            <i class="far fa-edit"></i>
            <% end %>
          </h4>
          <p>
            <%= s.start_date.strftime("%b %Y") %> - <%= s.end_date.strftime("%b %Y") %>
             |
            <%= s.duration %>
          </p>
          <p>
            <strong>Type:</strong>
            <%= s.study_type %>
          </p>
          <% if i < @user_other_studies.size - 1 %>
            <hr>
          <% end %>
        <% end %>
      </div>
      <!-- Languages -->
      <div class="form-profile">
        <h3>
          Languages
          <%= link_to new_user_profile_user_language_path(current_user.user_profile.id),
          class: "btn-add" do %>
          <i class="fas fa-plus"></i>
          <% end %>
        </h3>
        <% @user_languages.each_with_index do |s, i| %>
          <h4>
            <%= s.language.name %>
            <%= link_to edit_user_profile_user_language_path(@profile, s.id),
            class: "btn-add" do %>
            <i class="far fa-edit"></i>
            <% end %>
          </h4>
          <p>
            <strong>Proficiency:</strong>
            <%= s.proficiency %>%
          </p>
          <% if i < @user_languages.size - 1 %>
            <hr>
          <% end %>
        <% end %>
      </div>
      <!-- Work Preferences -->
      <div class="form-profile">
        <h3>
          Work Preferences
          <%= link_to new_user_profile_work_preference_path(current_user.user_profile.id),
          class: "btn-add" do %>
            <i class="fas fa-plus"></i>
          <% end %>
        </h3>
        <% @preferences.each_with_index do |s, i| %>
          <h4>
            <%= s.study.title %>
            <%= link_to edit_user_profile_work_preference_path(@profile, s.id),
            class: "btn-add" do %>
            <i class="far fa-edit"></i>
            <% end %>
          </h4>
          <p>
            <strong>Contract Type:</strong>
            <%= s.contract_type %>
          </p>
          <p>
            <strong>Objectives:</strong>
            <%= s.objectives %>
          </p>
          <% if i < @preferences.size - 1 %>
            <hr>
          <% end %>
        <% end %>
      </div>
      <!-- Skills -->
      <div class="form-profile">
        <h3>
          Skills
          <%= link_to new_user_profile_user_skill_path(current_user.user_profile.id),
          class: "btn-add" do %>
            <i class="fas fa-plus"></i>
          <% end %>
        </h3>
        <% @skills.each_with_index do |t, i| %>
          <h4>
            <%= t.skill.name %>
            <%= link_to user_profile_user_skill_path(@profile, t.id),
            method: :delete, class: "btn-add" do %>
              <i class="far fa-trash-alt"></i>
            <% end %>
          </h4>
        <% end %>
      </div>
      <!-- Working Experience -->
      <div class="form-profile">
        <h3>
          Working Experience
          <%= link_to new_user_profile_user_experience_path(current_user.user_profile.id),
          class: "btn-add" do %>
            <i class="fas fa-plus"></i>
          <% end %>
        </h3>
        <% @experiences.each_with_index do |s, i| %>
          <h4>
            <%= s.study.title %>
            <%= link_to edit_user_profile_user_experience_path(@profile, s.id),
            class: "btn-add" do %>
              <i class="far fa-edit"></i>
            <% end %>
          </h4>
          <p>
            <%= s.company_name %>
          </p>
          <p>
            <%= s.start_date.strftime("%b %Y") %> - <%= s.end_date.strftime("%b %Y") %>
             |
            <%= s.duration %>
          </p>
          <p>
            <strong>Contract Type:</strong>
            <%= s.contract_type %>
          </p>
          <p>
            <strong>Description:</strong>
            <%= s.description %>
          </p>
          <p>
            <strong>Skills:</strong>
            <%= s.skill.name %>
          </p>
          <p>
            <strong>Status:</strong>
            <%= s.status %>
          </p>
          <% if i < @experiences.size - 1 %>
            <hr>
          <% end %>
        <% end %>
      </div>
      <!-- Traits -->
      <div class="form-profile">
        <h3>
          Personality Traits
          <%= link_to new_user_profile_user_trait_path(current_user.user_profile.id),
          class: "btn-add" do %>
            <i class="fas fa-plus"></i>
          <% end %>
        </h3>
        <% @traits.each_with_index do |s, i| %>
          <h4>
            <%= s.trait.name %>
            <%= link_to user_profile_user_trait_path(@profile, s.id), method: :delete,
            class: "btn-add" do %>
            <i class="far fa-trash-alt"></i>
            <% end %>
          </h4>
          <p>
            <strong>Description:</strong>
            <%= s.trait.description %>
          </p>
          <% if i < @traits.size - 1 %>
            <hr>
          <% end %>
        <% end %>
      </div>
      <!-- Hobby -->
      <div class="form-profile">
        <h3>
          Hobbies
          <%= link_to new_user_profile_user_hobby_path(current_user.user_profile.id),
          class: "btn-add" do %>
            <i class="fas fa-plus"></i>
          <% end %>
        </h3>
        <% @hobbies.each_with_index do |t, i| %>
          <h4>
            <%= t.name %>
            <%= link_to edit_user_profile_user_hobby_path(@profile, t.id),
            class: "btn-add" do %>
            <i class="far fa-edit"></i>
            <% end %>
          </h4>
          <p>
            <strong>Category:</strong>
            <%= t.category %>
          </p>
          <% if i < @hobbies.size - 1 %>
            <hr>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<!-- Edit Profile Modal -->
<!-- <div class="modal fade" id="edit_profile" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Edit Your Profile</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="container gradient">
          <div class="form-login">
            <%= render 'form' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div> -->