config/routes.rb
Rails.application.routes.draw do
  devise_for :companies, path: 'companies', controllers: {
    sessions: 'companies/sessions'
  }
  devise_for :users, path: 'users', controllers: {
    sessions: 'users/sessions'
  }
  root to: 'pages#home'
  get 'pages/applicant_welcome', as: 'applicant_welcome'
  get 'pages/about_us', as: 'about_us'
  resources :user_profiles, only: [:show, :new, :create, :edit, :update] do
    resources :user_studies, only: [:index, :new, :create, :destroy, :edit, :update]
    resources :user_other_studies, only: [:index, :new, :create, :destroy, :edit, :update]
    resources :user_languages, only: [:index, :new, :create, :destroy, :edit, :update]
    resources :work_preferences, only: [:index, :new, :create, :destroy, :edit, :update]
    resources :user_skills, only: [:index, :new, :create, :destroy]
    resources :user_experiences, only: [:index, :new, :create, :destroy, :edit, :update]
    resources :user_traits, only: [:index, :new, :create, :destroy]
    resources :user_hobbies, only: [:index, :new, :create, :destroy, :edit, :update]
  end

end

app/models/work_preference.rb
class WorkPreference < ApplicationRecord
  belongs_to :user_profile
  belongs_to :study

  CONTRACT = ["Casual", "Contractor", "Full Time", "Internship", "Part Time",
              "Volunteer", "Work Experience"]

  validates :objectives, length: { maximum: 500 }
  validates :contract_type, presence: true
  validates :contract_type, inclusion: { in: CONTRACT }
end

app/controllers/work_preferences_controller.rb
class WorkPreferencesController < ApplicationController
  def new
    @profile = UserProfile.find(params[:user_profile_id])
    @preference = WorkPreference.new
  end

  def index
    @profile = UserProfile.find(params[:user_profile_id])
    @preference = WorkPreference.where(user_profile_id: params[:user_profile_id])
  end

  def create
    @profile = UserProfile.find(params[:user_profile_id])
    @preference = WorkPreference.new(preference_params)
    @preference.user_profile = current_user.user_profile
    if @preference.save
      redirect_to user_profile_path(:user_profile_id)
      flash[:notice] = "Preference Added"
    else
      flash[:alert] = "Please verify the following information:"
      render :new
      puts @preference.errors.full_messages
    end
  end

  def destroy
    @preference = WorkPreference.find(params[:id])
    @preference.destroy
    redirect_to user_profile_path(:user_profile_id)
    flash[:alert] = "Preference Removed"
  end

  def edit
    @profile = UserProfile.find(params[:user_profile_id])
    @preference = WorkPreference.find(params[:id])
  end

  def update
    @profile = UserProfile.find(params[:user_profile_id])
    @preference = WorkPreference.find(params[:id])
    @preference.update(preference_params)
    if @preference.save
      redirect_to user_profile_path(:user_profile_id)
      flash[:notice] = "Preference Updated"
    else
      flash[:alert] = "Please verify the following information:"
      render :new
      puts @preference.errors.full_messages
    end
  end

  private

  def preference_params
    params.require(:work_preference).permit(:user_profile_id, :study_id,
                                            :objectives, :contract_type)
  end
end

app/views/work_preferences/_form.html.erb
<%= simple_form_for [@profile, @preference] do |f| %>
  <%= f.association :study, input_html: {class: 'select2-list'},
  label: "Position" %>
  <%= f.input :contract_type, collection: ["Casual", "Contractor", "Full Time",
                                           "Internship", "Part Time",
                                           "Volunteer", "Work Experience"] %>
  <%= f.input :objectives, as: :text %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/work_preferences/edit.html.erb
<div class="container-fluid gradient">
  <div class="row">
    <div class="col-12 col-md-8 offset-md-2 col-lg-6 offset-lg-3">
      <div class="form-login">

        <h2 class="text-center">Edit your Working Preferences</h2>

        <%= render 'form' %>
        <%= link_to "Cancel", user_profile_path(current_user.user_profile.id),
        class: "btn btn-light" %>
        <%= link_to "Remove", user_profile_work_preference_path(params[:id]),
        method: :delete, class: "btn btn-danger" %>
      </div>
    </div>
  </div>
</div>

app/views/work_preferences/index.html.erb
<div class="container-fluid gradient-profile">
  <div class="row">
    <div class="col-12 col-md-8 offset-md-2 col-lg-6 offset-lg-3">
      <div class="form-profile">
        <nav class="nav nav-pills nav-fill">
          <%= link_to "About Me", user_profile_path(current_user.user_profile.id),
          class: "nav-item nav-link" %>
          <%= link_to "Education", user_profile_user_studies_path(current_user.user_profile.id),
          class: "nav-item nav-link" %>
          <%= link_to "Certifications", user_profile_user_other_studies_path(current_user.user_profile.id), class: "nav-item nav-link" %>
          <%= link_to "Languages", user_profile_user_languages_path(current_user.user_profile.id),
          class: "nav-item nav-link" %>
          <%= link_to "Work Preferences", user_profile_work_preferences_path(current_user.user_profile.id), class: "nav-item nav-link active" %>
          <%= link_to "Skills", user_profile_user_skills_path(current_user.user_profile.id),
          class: "nav-item nav-link" %>
          <%= link_to "Working Experience", user_profile_user_experiences_path(current_user.user_profile.id), class: "nav-item nav-link" %>
          <%= link_to "Personality Traits", user_profile_user_traits_path(current_user.user_profile.id), class: "nav-item nav-link" %>
          <%= link_to "Hobbies", user_profile_user_hobbies_path(current_user.user_profile.id),
          class: "nav-item nav-link" %>
        </nav>
        <h3>
          Work Preferences
          <%= link_to new_user_profile_work_preference_path(current_user.user_profile.id),
          class: "btn-add" do %>
            <i class="fas fa-plus"></i>
          <% end %>
        </h3>
        <% @preference.each_with_index do |s, i| %>
          <h4>
            <%= s.study.title %>
            <%= link_to edit_user_profile_work_preference_path(@profile, s.id),
            class: "btn-add" do %>
            <i class="far fa-edit"></i>
            <% end %>
          </h4>
          <p>
            <strong>Contract Type:</strong>
            <%= s.contract_type %>
          </p>
          <p>
            <strong>Objectives:</strong>
            <%= s.objectives %>
          </p>
          <% if i < @preference.size - 1 %>
            <hr>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/work_preferences/new.html.erb
<div class="container-fluid gradient">
  <div class="row">
    <div class="col-12 col-md-8 offset-md-2 col-lg-6 offset-lg-3">
      <div class="form-login">

        <h2 class="text-center">Add your Working Preferences to your Profile</h2>

        <%= render 'form' %>
        <%= link_to "Cancel", user_profile_path(current_user.user_profile.id),
        class: "btn btn-light" %>
      </div>
    </div>
  </div>
</div>