config/routes.rb
Rails.application.routes.draw do
  devise_for :companies, path: 'companies', controllers: {
    sessions: 'companies/sessions'
  }
  devise_for :users, path: 'users', controllers: {
    sessions: 'users/sessions'
  }
  root to: 'pages#home'
  get 'pages/applicant_welcome', as: 'applicant_welcome'
  get 'pages/about_us', as: 'about_us'
  resources :user_profiles, only: [:show, :new, :create, :edit, :update] do
    resources :user_studies, only: [:index, :new, :create, :destroy, :edit, :update]
    resources :user_other_studies, only: [:index, :new, :create, :destroy, :edit, :update]
    resources :user_languages, only: [:index, :new, :create, :destroy, :edit, :update]
    resources :work_preferences, only: [:index, :new, :create, :destroy, :edit, :update]
    resources :user_skills, only: [:index, :new, :create, :destroy]
    resources :user_experiences, only: [:index, :new, :create, :destroy, :edit, :update]
    resources :user_traits, only: [:index, :new, :create, :destroy]
    resources :user_hobbies, only: [:index, :new, :create, :destroy, :edit, :update]
  end

end

app/models/user_other_study.rb
class UserOtherStudy < ApplicationRecord
  belongs_to :user_profile
  belongs_to :other_study

  STUDY_TYPE = ["Certification", "License", "Course", "Other"]

  validates :study_type, presence: true, inclusion: { in: STUDY_TYPE }
  validates :start_date, presence: true
  validates :end_date, presence: true

  def check_date?
    start_date < end_date
  end

  def duration
    delta = self.end_date.to_i - self.start_date.to_i
    if delta < 2_629_800
      return "#{delta / 86_400} day(s)"
    elsif delta < 31_557_600
      return "#{delta / 2_529_800} month(s)"
    elsif delta > 31_557_600
      return "#{delta / 31_557_600} year(s)"
    end
  end
end

app/controllers/user_other_studies_controller.rb
class UserOtherStudiesController < ApplicationController
  def new
    @profile = UserProfile.find(params[:user_profile_id])
    @study = UserOtherStudy.new
  end

  def index
    @profile = UserProfile.find(params[:user_profile_id])
    @study = UserOtherStudy.where(user_profile_id: params[:user_profile_id])
  end

  def create
    @profile = UserProfile.find(params[:user_profile_id])
    @study = UserOtherStudy.new(study_params)
    @study.user_profile = current_user.user_profile
    if @study.check_date? == false
      flash[:alert] = "Please enter a valid date"
      render :new
    elsif @study.save
      redirect_to user_profile_path(:user_profile_id)
      flash[:notice] = "Study Added"
    else
      flash[:alert] = "Please verify the following information:"
      render :new
      puts @study.errors.full_messages
    end
  end

  def destroy
    @study = UserOtherStudy.find(params[:id])
    @study.destroy
    redirect_to user_profile_path(:user_profile_id)
    flash[:alert] = "Study Removed"
  end

  def edit
    @profile = UserProfile.find(params[:user_profile_id])
    @study = UserOtherStudy.find(params[:id])
  end

  def update
    @profile = UserProfile.find(params[:user_profile_id])
    @study = UserOtherStudy.find(params[:id])
    @study.update(study_params)
    if @study.check_date? == false
      flash[:alert] = "Please enter a valid date"
      render :new
    elsif @study.save
      redirect_to user_profile_path(:user_profile_id)
      flash[:notice] = "Study Updated"
    else
      flash[:alert] = "Please verify the following information:"
      render :new
      puts @study.errors.full_messages
    end
  end

  private

  def study_params
    params.require(:user_other_study).permit(:user_profile_id, :other_study_id,
     :study_type, :start_date, :end_date)
  end
end

app/views/user_other_studies/_form.html.erb
<%= simple_form_for [@profile, @study] do |f| %>
  <%= f.association :other_study, label: "Title" %>
  <%= f.input :study_type, collection: ["Certification", "License", "Course",
                                        "Other"], label: "Type" %>
  <%= f.input :start_date, as: :string, input_html: { class: 'datepicker start_date' } %>
  <%= f.input :end_date, as: :string, input_html: { class: 'datepicker end_date' } %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/user_other_studies/edit.html.erb
<div class="container-fluid gradient">
  <div class="row">
    <div class="col-12 col-md-8 offset-md-2 col-lg-6 offset-lg-3">
      <div class="form-login">

        <h2 class="text-center">Edit Study</h2>

        <%= render 'form' %>
        <%= link_to "Cancel", user_profile_path(current_user.user_profile.id),
        class: "btn btn-light" %>
        <%= link_to "Remove", user_profile_user_other_study_path(params[:id]),
        method: :delete, class: "btn btn-danger" %>
      </div>
    </div>
  </div>
</div>

app/views/user_other_studies/index.html.erb
<div class="container-fluid gradient-profile">
  <div class="row">
    <div class="col-12 col-md-8 offset-md-2 col-lg-6 offset-lg-3">
      <div class="form-profile">
        <nav class="nav nav-pills nav-fill">
          <%= link_to "About Me", user_profile_path(current_user.user_profile.id),
          class: "nav-item nav-link" %>
          <%= link_to "Education", user_profile_user_studies_path(current_user.user_profile.id),
          class: "nav-item nav-link" %>
          <%= link_to "Certifications", user_profile_user_other_studies_path(current_user.user_profile.id), class: "nav-item nav-link active" %>
          <%= link_to "Languages", user_profile_user_languages_path(current_user.user_profile.id),
          class: "nav-item nav-link" %>
          <%= link_to "Work Preferences", user_profile_work_preferences_path(current_user.user_profile.id), class: "nav-item nav-link" %>
          <%= link_to "Skills", user_profile_user_skills_path(current_user.user_profile.id),
          class: "nav-item nav-link" %>
          <%= link_to "Working Experience", user_profile_user_experiences_path(current_user.user_profile.id), class: "nav-item nav-link" %>
          <%= link_to "Personality Traits", user_profile_user_traits_path(current_user.user_profile.id), class: "nav-item nav-link" %>
          <%= link_to "Hobbies", user_profile_user_hobbies_path(current_user.user_profile.id),
          class: "nav-item nav-link" %>
        </nav>
        <h3>
          Certifications
          <%= link_to new_user_profile_user_other_study_path(current_user.user_profile.id),
          class: "btn-add" do %>
          <i class="fas fa-plus"></i>
          <% end %>
        </h3>
        <% @study.each_with_index do |s, i| %>
          <h4>
            <%= s.other_study.title %>
            <%= link_to edit_user_profile_user_other_study_path(@profile, s.id), class: "btn-add" do %>
            <i class="far fa-edit"></i>
            <% end %>
          </h4>
          <p>
            <%= s.start_date.strftime("%b %Y") %> - <%= s.end_date.strftime("%b %Y") %>
             |
            <%= s.duration %>
          </p>
          <p>
            <strong>Type:</strong>
            <%= s.study_type %>
          </p>
          <% if i < @study.size - 1 %>
            <hr>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/user_other_studies/new.html.erb
<div class="container-fluid gradient">
  <div class="row">
    <div class="col-12 col-md-8 offset-md-2 col-lg-6 offset-lg-3">
      <div class="form-login">

        <h2 class="text-center">Add Other Studies to your Profile</h2>

        <%= render 'form' %>
        <%= link_to "Cancel", user_profile_path(current_user.user_profile.id),
        class: "btn btn-light" %>
      </div>
    </div>
  </div>
</div>